version: '3.1'

services:
  app:
    container_name: yatc-server
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:3000
      - 9229:9229
    environment:
      - NODE_ENV=development
      - PORT=3000
    links:
      - redis
    depends_on:
      - redis
      - database

  redis:
    image: redis
    container_name: yatc-redis
    ports:
      - 6379:6379

  database:
    image: postgres
    restart: always
    container_name: yatc-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpwd
      - POSTGRES_DB=yatcdb

  dbadminer:
    image: adminer
    container_name: yatc-db-adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - database
    depends_on:
      - database
    environment:
      - ADMINER_DEFAULT_SERVER=localhost
      - ADMINER_DESIGN=price
      - ADMINER_DRIVER=pgsql
